import { Inter,Montserrat } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '../components/Header'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'chaapa ride',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" className='bg-[#bd3839]'>
      <body className={inter.className}>
        <Header/>
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}
